### ISSUE TITLE
pepper vs. salt has different `test.arg_repr` output types

### ISSUE THREAD

**Issue by goodboy** [saltstack/pepper#99] opened 2017-03-01 06:35 UTC
When using `pepper` versus the standard `salt` command you get different results in terms of returned data types. 

This seems related to #57 but different in the details.

```bash
(envsalt)  >>> pepper -a pam --username=saltvirt --password=saltvirt 'sip-cannon' test.arg_repr trunktest2 2 '2048' image=/var/lib/libvit/images/centos66.qcow2 enable_vnc=True config='{"master": "goodboy.qa.sangoma.local"}' start=False enable_qcow=True                     
{
    "return": [
        {
            "sip-cannon": {
                "args": "('trunktest2', '2', '2048')",
                "kwargs": "{'__pub_user': 'saltvirt', '__pub_arg': ['trunktest2', '2', '2048', 'image=/var/lib/libvirt/images/centos66.qcow2', 'enable_vnc=True', 'config={\"master\": \"goodboy.qa.sangoma.local\"}', 'start=False', 'enable_qcow=True'], 'start': False, 'config
': {'master': 'goodboy.qa.sangoma.local'}, 'image': '/var/lib/libvirt/images/centos66.qcow2', '__pub_fun': 'test.arg_repr', 'enable_qcow$
: True, '__pub_jid': '20170301004836803665', '__pub_tgt': 'sip-cannon', '__pub_tgt_type': 'glob', 'enable_vnc': True, '__pub_ret': ''}"
            }
        }
    ]
}
 
(envsalt)  >>> sudo salt 'sip-cannon' test.arg_repr trunktest2 2 2048 image=/var/lib/libvirt/images/centos66.qcow2 enable_vnc=True con$
ig='{"master": "goodboy.qa.sangoma.local"}' start=False enable_qcow=True
sip-cannon:
    ----------
    args:
        ('trunktest2', 2, 2048)
    kwargs:
        {'__pub_user': 'sudo_tyler', '__pub_arg': ['trunktest2', 2, 2048, {'enable_qcow': True, 'image': '/var/lib/libvirt/images/centos66.qcow2', 'start': False, 'config': {'master': 'goodboy.qa.sangoma.local'}, 'enable_vnc': True}], 'enable_qcow': True, 'config': {'master': 'goodboy.qa.sangoma.local'}, 'image': '/var/lib/libvirt/images/centos66.qcow2', '__pub_fun': 'test.arg_repr', 'start': False, '__pub_id': '20170301004859437566', '__pub_tgt': 'sip-cannon', '__pub_tgt_type': 'glob', 'enable_vnc': True, '__pub_ret': ''}
```

Notably the `arg` array contains different types (in this case most obviously `int` versus `str`),
- `pepper`:
```python
('trunktest2', '2', '2048')
```

- `salt`: 
```python
('trunktest2', 2, 2048)
```

In my case this is turn causes a parsing problem downstream in the `salt.modules.virt.init()` function:
```
00:34:44 [ 2382] [DEBUG   ] Generating VM XML                                                                                            
libvirt: Domain Config error : XML error: Invalid value '20482048204820482048204820482048204820482048204820482048204820482048204820482048
20482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482
04820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820
48204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204
82048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048
20482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482
04820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820
482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204                                
```

**Comment by goodboy** [comment] 2017-03-01 06:47
Oh and just to be extra thorough, if you watch the `salt-api` trace logs you'll see the same types as well:

```
00:57:13 [28149] [TRACE   ] get_event() received = {'tag': 'salt/job/20170301005713642409/ret/sip-cannon', 'data': {'fun_args': ['trunkte
st2', '2', '2048', 'image=/var/lib/libvirt/images/centos66.qcow2', 'enable_vnc=True', 'config={"master": "goodboy.qa.sangoma.local"}', 's
tart=False', 'enable_qcow=True'], 'jid': '20170301005713642409', 'return': {'args': "('trunktest2', '2', '2048')", 'kwargs': '{\'__pub_us
er\': \'saltvirt\', \'__pub_arg\': [\'trunktest2\', \'2\', \'2048\', \'image=/var/lib/libvirt/images/centos66.qcow2\', \'enable_vnc=True\
', \'config={"master": "goodboy.qa.sangoma.local"}\', \'start=False\', \'enable_qcow=True\'], \'start\': False, \'config\': {\'master\': 
\'goodboy.qa.sangoma.local\'}, \'image\': \'/var/lib/libvirt/images/centos66.qcow2\', \'__pub_fun\': \'test.arg_repr\', \'enable_qcow\': 
True, \'__pub_jid\': \'20170301005713642409\', \'__pub_tgt\': \'sip-cannon\', \'__pub_tgt_type\': \'glob\', \'enable_vnc\': True, \'__pub
_ret\': \'\'}'}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-03-01T05:57:13.698160', 'fun': 'test.arg_repr', 'id': '
sip-cannon'}}

**Comment by whiteinge** [comment] 2017-03-01 17:31
Coincidentally, there's [an open PR in Salt](https://github.com/saltstack/salt/pull/39472) that has a fix to make the `foo=Foo` processing identical to the `salt` CLI processing. Until that fix is merged and released the best way to preserve types is to use the new `--json` flag in Pepper (#98) to send JSON instead of name=value arguments.

**Comment by whiteinge** [comment] 2017-03-01 17:34
Ninja edit: I failed at reading -- that PR is a fix for calling Runners. I'm not aware of a mismatch when calling execution functions on minions.

I'll take a closer look at this.

**Comment by goodboy** [comment] 2017-03-01 18:59
@whiteinge yeah I think I found the reason after using the python api.

`args` are [shipped verbatim](https://github.com/saltstack/pepper/blob/develop/pepper/cli.py#L318) as parsed strings as opposed to converting `key=val` pairs into `**kwargs` as is done with the  [`runner` client](https://github.com/saltstack/pepper/blob/develop/pepper/cli.py#L335).

The tricky part I'm not sure how to handle is how to deliver parsed `**kwargs` for each underlying `client` type. For example [`local`](https://github.com/saltstack/pepper/blob/develop/pepper/libpepper.py#L249) takes them in a `kwarg` `dict` whilst [`runner`](https://github.com/saltstack/pepper/blob/develop/pepper/libpepper.py#L348) takes them as `**kwargs` (which I don't think works by the way in salt core).

I can rummage up a PR for at least the `local` client if you're cool with it.

**Comment by whiteinge** [comment] 2017-03-01 21:39
I haven't had a chance to take a look at this yet, but shipping args verbatim as `name=value` pairs is what we want Pepper to do. The reason for that is that the `salt` CLI command gets that **same** format from the shell and Salt actually splits them (and also runs the right-hand side through the YAML parser) which is what that `parse_input` function does. Pepper needs to be updated to also do that for runner calls (once the above PR is merged).

**Comment by goodboy** [comment] 2017-03-02 00:05
@whiteinge
>shipping args verbatim as name=value pairs is what we want Pepper to do

kk that's fine then but I guess it's besides the point of the missing `type` casting? 

> Salt actually splits them (and also runs the right-hand side through the YAML parser) which is what that parse_input function does.

^ would make me think that once that's fixed then maybe this type difference problem goes away?

**Comment by whiteinge** [comment] 2017-03-02 04:31
Yeah, I think so. Running the right-hand side through the YAML parser is what performs the type casting. E.g. `foo=True` becomes `{"foo": true}`. And that's what the CLI relies on for that too.

**Comment by whiteinge** [comment] 2017-03-02 19:14
I can reproduce this. The problem is somewhere in salt-api or in Salt. Trying to find the culprit.

If you need a workaround in the meantime, sending JSON via the `--json` flag to Pepper will allow you to specify the right data types up-front rather than relying on the `name=value` parsing in Salt.

**Comment by goodboy** [comment] 2017-03-02 19:16
@whiteinge nice and thanks for looking into it.

Actually the main problem for me was it exposed a bug in `salt-virt` which I now have a fix for and will get in later today.
So all good on my end :+1:

**Closed as completed** 2019-03-12 09:40 UTC

**Comment by gtmanfred** [comment] 2019-03-12 14:33
This will be fixed with the neon release of salt.

**Comment by goodboy** [comment] 2019-04-25 16:21
@gtmanfred woot glad to see it finally landed :)
